dist: trusty
script: "/bin/true"
notifications:
  email: false
  slack:
    rooms:
      secure: FIj81JDS6JeLvouEY/SVuDG2uXI9Z45sJ4e9uhFsEtm25ZE/2uw5HK1rDf+SaOfv6ri9+VxSApB+PabfCdEioR7C7oxNZPpdyLAOVEnci8dws4S52a/hC/vqUia5ahhggVMwZ5Muw+bErZHn7Z0q60IV9aXYha7MptyW1nGfxDyhHcPsLmaDzx412+uu9pO33/FXlU3MWOPXjK+TNwtO3u/lXuqYi9fLvqR0yeC0HO9UzIHmkUER3Nd8bKUGaC4uCWrs6S4/si36IyYDCz62+nKzYseF2yYKoku4SI0ifkh/+6SUiJjZYhRPUFsMevYsMMCMSrgDWKhDuUsGeVGPlHEjdJF1bXdSD6yxDR64MyTXf3uyjqUdid/VAzRSdfxQIVK5MZI1tHFs5yjOtHpvZC4p4JOneRyikSbkerg6gpRr5k/8nN6CXcH5pw8RaG8ONPfVNXCsf+MngMR1i8NbiBTI+Ze6Q36baWz0sjw/+qmiKM0DOTbYJo0jh9rmuSCep1Hh/brkOzZNA+mKc0t1gm7Ulf79JNu0g+62NQhOi080i556oSc2ufjufg4mht8/yc0GHfPwg05TVKdt/Itq7O3CABddOiNvSe48QbF+Mrel17+B2n1UijkrB7RMRw9DUVKmg3ogsFt8qONJAs/RTPO52ySWVOzHpU0Krxb3kZ4=
