dist: xenial
env:
  global:
  - TFBIN_DIR=$HOME/tfbin
  - TERRAFORM_VERSION=0.11.13
install:
- "./scripts/download_terraform.sh $TERRAFORM_VERSION"
script:
- "~/tfbin/terraform fmt -write=false -diff=true -check"
notifications:
  email: false
  slack:
    secure: lBEawK0rhxIuo7F8YuJvpN350c5oBoOobKbLgFlZ3CJL84Fa3hSOsQTaOohSb9SffYyQWTCwXtAfE6QBAQ2CWR3gfssfb+FBHgsmRvd4e8xYifzOvow+95A2/Vj86sYG/zfp2e96QVkBdv3tOHHPwLWBUhf++BkH+xo8C0I0uq3+d7PQl4iisw7YSlVoAgG4s50F2kus7zF313iVMjY0TQa4y4mnZLg7RKjkt5Y6cx0ROk4RM4KwJ8nHyap0SOBq2GdZm882z7CCXSq/HkABxjbTobyVVEa+oxZD1q2t2+lVUfJrmNXjjj2wS+koZn1lmfxX3+FUx2Z7okClbpiQ/9IlWBTKRxHx87xnTIjayGf3+qnPILgmTGs88XlckjhQxTSEAQExDUfXMTboPyx6hzzfF0ol5VXpPh907HbUIGc2NGb8MphPV8KwpxTVKdi0GcdSna7J7H+lrPIoap9gvZ62p4Gk3Jthi+DI+HxW22aloYRHdH5K7fuxauaCUuCyXMLIYQVK6iPmwk3Q+WesVqJKUsrTeiKfnxT1Jx2E3Glq9OhLPhrvP4EsXl2J/MrsrbuFgrz78foEMJ154jbGWl+hmTbbDNuA0P74l+PdKqyzQqyF4T923UcG/il8eBcZO5xxJKcrm/W6B9VAiQSAhVo3hKxx9VhEkNfB6sDRYPM=
